name: test_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter_bloc: ^8.0.1
  flutter_native_splash: ^2.0.5
  flutter_svg: ^2.0.7
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get_it: ^7.2.0
  http: ^0.13.4
  injectable: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  loader_overlay: ^2.3.0
  provider: ^6.0.2
  shared_preferences: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.4

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: ubuntu
      fonts:
        - asset: assets/fonts/ubuntu-300.ttf
          weight: 300
        - asset: assets/fonts/ubuntu-400.ttf
          weight: 400
        - asset: assets/fonts/ubuntu-500.ttf
          weight: 500
        - asset: assets/fonts/ubuntu-700.ttf
          weight: 700